### ISSUE TITLE
Missing mention of disk stats unit in reference

### ISSUE THREAD

**Issue by r9host** [mackerelio/go-osstat#17]
I don't see anywhere in the reference about measurement unit of ReadsCompleted and WritesCompleted fields of disk stats type. Are they read/write coumy or read/witten bytes? If they counts, is there anyway to get rKB/s and wKB/s displayed by iostat?

**Comment by lufia** [comment]
There are the total number of reads/writes completed successfully.

Currently, `disk.Get` reads statistics from **/proc/diskstats**, and uses only both the field 1 and 5 in it.
https://www.kernel.org/doc/Documentation/iostats.txt
