### ISSUE TITLE
interface metrics are wrong on docker

### ISSUE THREAD

**Issue by koooge** [mackerelio/go-osstat#8]
Hi ✋ 
I'm using mackerel-agent(docker), and felt *interface* metrics are something wrong.
https://github.com/mackerelio/go-osstat/blob/master/network/network_linux.go#L17
Does mackerel-agent(docker) reads procfs on the container? But I'd like it to read the value on host machine. My mackerel-agent doesn't mount host's /proc though..

**Comment by shibayu36** [comment]
You mean that you execute mackerel-agent in adocker container? If so, mackerel-agent(in a container) cannot fetch the interface metrics of the host machine.

If you want to fetch the interface metrics of the host machine, you need to run mackerel-agent in the host machine.

If you want to fetch both the metrics of the host machine and the metrics of the container, for example, there is the following way.

- You execute mackerel-agent on the host machine.
- You use [mackerel-plugin-docker](https://github.com/mackerelio/mackerel-agent-plugins/tree/master/mackerel-plugin-docker) to fetch the metrics of containers running on the host machine

**Comment by koooge** [comment]
> You mean that you execute mackerel-agent in adocker container?
Yes, I mean.

> If you want to fetch both the metrics of the host machine and the metrics of the container, for example, there is the following way.
Hmm, okay but it feels like not easy to deploy services on hosts. I expected behavior like https://github.com/prometheus/node_exporter.

I will close this issue since it seems expected behavior. Thanks!

**Comment by hayajo** [comment]
How about running the container with '--net=host' flag ?
